/**
 * all-features.spec.ts
 *
 * Builds a single .docx from scratch using every feature in mdocxengine:
 *   Page layout · Header/Footer · Styles · Paragraphs · Runs · Tables ·
 *   Images · Footnotes · Endnotes · Bookmarks · Cross-references ·
 *   Citations · Captions · TOC · Numbering · Metadata · Comments ·
 *   Tracked changes · Sections · Shapes
 *
 * Output: samples/outputs/all-features.docx
 */

import { describe, test, expect, beforeAll } from "vitest";
import path from "path";
import fs from "fs";
import {
  Mdocxengine,
  Paragraph,
  Run,
  Table,
  EMU_PER_INCH,
} from "@/index";

const INPUT  = path.resolve("samples/example.docx");
const OUTPUT = path.resolve("samples/outputs/all-features.docx");

// Minimal 1×1 white PNG
const TINY_PNG = Buffer.from(
  "89504e470d0a1a0a0000000d4948445200000001000000010802000000" +
  "90012e0000000c49444154789c6260f8cfc000000002000173e5494c0000000049454e44ae426082",
  "hex",
);

let engine: Mdocxengine;

// ── helpers ───────────────────────────────────────────────────────────────────

function para(text: string, style?: string): Paragraph {
  const p = new Paragraph({ $: {}, "w:r": [] } as any);
  p.addRun(Run.fromText(text));
  if (style) p.applyStyle(style);
  return p;
}

function heading(level: 1 | 2 | 3, text: string): Paragraph {
  return para(text, `Heading${level}`);
}

// ─────────────────────────────────────────────────────────────────────────────

describe("all-features — every mdocxengine capability in one document", () => {
  beforeAll(async () => {
    fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
    engine = await Mdocxengine.loadFromFile(INPUT);
  });

  // ── 1. Metadata ─────────────────────────────────────────────────────────────

  test("1. metadata — set core and app properties", async () => {
    await engine.metadata.setCoreProperties({
      title:          "mdocxengine Feature Demo",
      subject:        "Integration test covering every manager",
      creator:        "mdocxengine",
      description:    "Auto-generated document showcasing all library features",
      lastModifiedBy: "mdocxengine test suite",
    });

    await engine.metadata.setAppProperties({ application: "mdocxengine" });

    const core = await engine.metadata.getCoreProperties();
    expect(core.title).toBe("mdocxengine Feature Demo");
    expect(core.creator).toBe("mdocxengine");
  });

  // ── 2. Page layout ──────────────────────────────────────────────────────────

  test("2. page layout — A4, portrait, normal margins", async () => {
    await engine.pageLayout.setPageSizePreset("A4", "portrait");
    await engine.pageLayout.setMarginPreset("normal");

    const size    = await engine.pageLayout.getPageSize();
    const margins = await engine.pageLayout.getMargins();
    expect(size.orientation).toBe("portrait");
    expect(margins.top).toBe(1440);
  });

  // ── 3. Header & footer ──────────────────────────────────────────────────────

  test("3a. header — add default header", async () => {
    await engine.header.addHeader("mdocxengine Feature Demo", "default");
    const xml = engine.zip.readAsText("word/document.xml")!;
    expect(xml).toContain("w:headerReference");
  });

  test("3b. footer — add default footer", async () => {
    await engine.footer.addFooter("Generated by mdocxengine", "default");
    const xml = engine.zip.readAsText("word/document.xml")!;
    expect(xml).toContain("w:footerReference");
  });

  // ── 4. Styles ───────────────────────────────────────────────────────────────

  test("4. styles — add a custom character style", async () => {
    await engine.styles.addStyle({
      $: { "w:type": "character", "w:styleId": "CustomHighlight" },
      "w:name": { $: { "w:val": "Custom Highlight" } },
      "w:rPr": {
        "w:highlight": { $: { "w:val": "yellow" } },
        "w:b": {},
      },
    });

    const styles = await engine.styles.listStyles();
    expect(styles.some((s) => s.id === "CustomHighlight")).toBe(true);
  });

  // ── 5. Paragraphs & runs ────────────────────────────────────────────────────

  test("5. paragraphs — insert title and intro paragraphs", async () => {
    const title = para("mdocxengine Feature Demo", "Title");

    const intro = new Paragraph({ $: {}, "w:r": [] } as any);
    const bold  = Run.fromText("automatically generated");
    bold.setBold(); bold.setItalic();
    intro.addRun(Run.fromText("This document was "));
    intro.addRun(bold);
    intro.addRun(Run.fromText(" by the mdocxengine library, exercising every manager."));

    await engine.document.insertParagraph(title, 0);
    await engine.document.insertParagraph(intro, 1);

    const paragraphs = await engine.document.getParagraphs();
    expect(paragraphs.length).toBeGreaterThanOrEqual(2);
  });

  // ── 6. Numbering ────────────────────────────────────────────────────────────

  test("6. numbering — add bulleted list", async () => {
    await engine.document.insertParagraph(heading(1, "Features Overview"));

    const defs  = await engine.numbering.getNumberingDefinitions();
    const items = [
      "Paragraph & Run formatting",
      "Tables with borders and shading",
      "Images and media management",
      "Headers, footers, and sections",
      "Comments, tracked changes, shapes",
    ];

    for (const item of items) {
      const p = para(item);
      if (defs.length > 0) await engine.numbering.applyNumbering(p, defs[0].numId, 0);
      await engine.document.insertParagraph(p);
    }

    const paragraphs = await engine.document.getParagraphs();
    expect(paragraphs.length).toBeGreaterThan(5);
    // Verify the XML contains the inserted list text
    const docXml = engine.zip.readAsText("word/document.xml")!;
    expect(docXml).toContain("Paragraph");
  });

  // ── 7. Table ────────────────────────────────────────────────────────────────

  test("7. table — insert a data table", async () => {
    await engine.document.insertParagraph(heading(1, "Data Table"));

    const table = new Table({
      "w:tr": [
        { "w:tc": [
          { "w:p": { "w:r": { "w:t": "Manager" } } },
          { "w:p": { "w:r": { "w:t": "Part" } } },
          { "w:p": { "w:r": { "w:t": "Status" } } },
        ]},
        { "w:tc": [
          { "w:p": { "w:r": { "w:t": "DocumentManager" } } },
          { "w:p": { "w:r": { "w:t": "word/document.xml" } } },
          { "w:p": { "w:r": { "w:t": "✓" } } },
        ]},
        { "w:tc": [
          { "w:p": { "w:r": { "w:t": "CommentsManager" } } },
          { "w:p": { "w:r": { "w:t": "word/comments.xml" } } },
          { "w:p": { "w:r": { "w:t": "✓" } } },
        ]},
      ],
    } as any);

    await engine.document.insertTable(table);

    const tables = await engine.document.getTables();
    expect(tables.length).toBeGreaterThanOrEqual(1);
    expect(tables[tables.length - 1].getCellText(0, 0)).toBe("Manager");
  });

  // ── 8. Image ────────────────────────────────────────────────────────────────

  test("8. media — insert a PNG image", async () => {
    await engine.document.insertParagraph(heading(1, "Image"));

    const { imagePath, relId } = await engine.media.insertImage(TINY_PNG, "png");
    expect(imagePath).toMatch(/word\/media\//);
    expect(relId).toMatch(/^rId/);

    const images = await engine.media.listImages();
    expect(images.some((img) => img.path === imagePath)).toBe(true);
  });

  // ── 9. Footnotes & endnotes ─────────────────────────────────────────────────

  test("9a. footnotes — add a footnote", async () => {
    await engine.document.insertParagraph(heading(1, "References"));

    const { id } = await engine.footnotes.addFootnote(
      "This is the footnote body text, rendered at the bottom of the page.",
    );

    const footnotes = await engine.footnotes.getFootnotes();
    expect(footnotes.some((f) => f.id === id)).toBe(true);

    // Verify the footnotes XML part exists and contains the text
    const xml = engine.zip.readAsText("word/footnotes.xml")!;
    expect(xml).toContain("footnote body text");
  });

  test("9b. endnotes — add an endnote", async () => {
    const { id } = await engine.endnotes.addEndnote(
      "Endnote body: appears at the end of the document section.",
    );

    const endnotes = await engine.endnotes.getEndnotes();
    expect(endnotes.some((e) => e.id === id)).toBe(true);

    const xml = engine.zip.readAsText("word/endnotes.xml")!;
    expect(xml).toContain("end of the document section");
  });

  // ── 10. Bookmarks & cross-references ────────────────────────────────────────

  test("10. cross-references — bookmark + cross-ref runs", async () => {
    const paragraphs = await engine.document.getParagraphs();
    // Use second-to-last paragraph to avoid sectPr paragraph
    const targetIdx  = Math.max(0, paragraphs.length - 2);

    const bmId = await engine.crossRef.addBookmark(targetIdx, "FeatureSection", "");
    expect(bmId).toBeGreaterThanOrEqual(0);

    const bookmarks = await engine.crossRef.getBookmarks();
    expect(bookmarks.some((b) => b.name === "FeatureSection")).toBe(true);

    const refRuns = engine.crossRef.createCrossRefRuns("FeatureSection", "Feature Section");
    expect(refRuns.length).toBe(5);
  });

  // ── 11. Citations ───────────────────────────────────────────────────────────

  test("11. citations — add a source and bibliography", async () => {
    await engine.document.insertParagraph(heading(1, "Bibliography"));

    await engine.citations.addSource({
      tag:    "mdocxengine2026",
      title:  "mdocxengine: A TypeScript OOXML Library",
      author: "mdocxengine Contributors",
      year:   "2026",
      type:   "Misc",
    });

    await engine.citations.insertBibliography();

    const sources = await engine.citations.getSources();
    expect(sources.some((s) => s.tag === "mdocxengine2026")).toBe(true);
  });

  // ── 12. Captions ────────────────────────────────────────────────────────────

  test("12. captions — insert figure and table captions", async () => {
    await engine.document.insertParagraph(heading(1, "Figures and Tables"));

    const paragraphs = await engine.document.getParagraphs();
    const insertAt   = paragraphs.length - 1;

    await engine.captions.insertCaption(insertAt, {
      label:    "Figure",
      title:    "Architecture overview of mdocxengine",
      position: "after",
    });

    await engine.captions.insertCaption(insertAt + 1, {
      label:    "Table",
      title:    "Manager inventory",
      position: "after",
    });

    const figureCaptions = await engine.captions.getCaptions("Figure");
    const tableCaptions  = await engine.captions.getCaptions("Table");
    expect(figureCaptions.length).toBeGreaterThanOrEqual(1);
    expect(tableCaptions.length).toBeGreaterThanOrEqual(1);
  });

  // ── 13. Table of Contents ───────────────────────────────────────────────────

  test("13. TOC — insert table of contents", async () => {
    await engine.toc.insertTOC({ title: "Table of Contents", maxDepth: 3, useHyperlinks: true }, 2);

    const xml = engine.zip.readAsText("word/document.xml")!;
    expect(xml).toContain("TOC");
  });

  // ── 14. Comments ────────────────────────────────────────────────────────────

  test("14a. comments — add and retrieve a comment", async () => {
    const paragraphs = await engine.document.getParagraphs();
    expect(paragraphs.length).toBeGreaterThan(0);
    const targetIdx = Math.max(0, Math.min(3, paragraphs.length - 2));

    const id = await engine.comments.addComment(
      targetIdx,
      "Reviewer",
      "This section looks great — no changes needed.",
    );

    expect(id).toBeGreaterThanOrEqual(1);

    const comments = await engine.comments.getComments();
    const found    = comments.find((c) => c.id === id);
    expect(found).toBeDefined();
    expect(found!.author).toBe("Reviewer");
    expect(found!.text).toBe("This section looks great — no changes needed.");
  });

  test("14b. comments — delete a comment", async () => {
    const paragraphs = await engine.document.getParagraphs();
    const targetIdx  = Math.max(0, Math.min(1, paragraphs.length - 2));

    const before = (await engine.comments.getComments()).length;
    const id     = await engine.comments.addComment(targetIdx, "Editor", "Remove this.");
    await engine.comments.deleteComment(id);
    const after  = (await engine.comments.getComments()).length;
    expect(after).toBe(before);
  });

  // ── 15. Tracked changes ─────────────────────────────────────────────────────

  test("15a. tracked changes — getRevisions on clean doc", async () => {
    const revisions = await engine.trackedChanges.getRevisions();
    expect(Array.isArray(revisions)).toBe(true);
  });

  test("15b. tracked changes — acceptAll and rejectAll run without error", async () => {
    await expect(engine.trackedChanges.acceptAll()).resolves.not.toThrow();
    await expect(engine.trackedChanges.rejectAll()).resolves.not.toThrow();
  });

  // ── 16. Sections ────────────────────────────────────────────────────────────

  test("16a. sections — getSections returns at least the final section", async () => {
    const sections = await engine.sections.getSections();
    expect(sections.length).toBeGreaterThanOrEqual(1);
    expect(sections[sections.length - 1].isFinal).toBe(true);
  });

  test("16b. sections — add section break then remove it", async () => {
    const paragraphs = await engine.document.getParagraphs();
    const breakIdx   = Math.max(0, Math.min(5, paragraphs.length - 2));

    const before = (await engine.sections.getSections()).length;
    await engine.sections.addSectionBreak(breakIdx, "nextPage");
    const after  = (await engine.sections.getSections()).length;
    expect(after).toBe(before + 1);

    await engine.sections.removeSectionBreak(breakIdx);
    const restored = (await engine.sections.getSections()).length;
    expect(restored).toBe(before);
  });

  test("16c. sections — setSectionLayout on final section", async () => {
    const sections = await engine.sections.getSections();
    const finalIdx = sections[sections.length - 1].index;

    await engine.sections.setSectionLayout(finalIdx, {
      pageSize: { width: 11906, height: 16838 },
      margins:  { top: 1440, bottom: 1440, left: 1800, right: 1800 },
    });

    const updated = await engine.sections.getSections();
    expect(updated[updated.length - 1].pageSize?.width).toBe(11906);
  });

  // ── 17. Shapes ──────────────────────────────────────────────────────────────

  test("17a. shapes — insert a floating text box", async () => {
    await engine.document.insertParagraph(heading(1, "Shapes"));

    const id = await engine.shapes.insertTextBox({
      text:        "Hello from mdocxengine ShapeManager!",
      fillColor:   "E7F3FF",
      borderColor: "4472C4",
      size:        { width: 3 * EMU_PER_INCH, height: EMU_PER_INCH },
      position:    { x: EMU_PER_INCH, y: EMU_PER_INCH },
    });

    expect(id).toBeGreaterThanOrEqual(1);

    const shapes = await engine.shapes.getShapes();
    const found  = shapes.find((s) => s.id === id);
    expect(found).toBeDefined();
    expect(found!.type).toBe("textbox");
  });

  test("17b. shapes — insert preset shapes", async () => {
    const rectId    = await engine.shapes.insertShape("rect",       { fillColor: "4472C4", size: { width: EMU_PER_INCH, height: EMU_PER_INCH } });
    const ellipseId = await engine.shapes.insertShape("ellipse",    { fillColor: "ED7D31", size: { width: EMU_PER_INCH, height: EMU_PER_INCH }, position: { x: 2 * EMU_PER_INCH, y: EMU_PER_INCH } });
    const arrowId   = await engine.shapes.insertShape("rightArrow", { fillColor: "70AD47", size: { width: 2 * EMU_PER_INCH, height: EMU_PER_INCH }, position: { x: 4 * EMU_PER_INCH, y: EMU_PER_INCH } });

    const shapes = await engine.shapes.getShapes();
    expect(shapes.find((s) => s.id === rectId)?.type).toBe("rect");
    expect(shapes.find((s) => s.id === ellipseId)?.type).toBe("ellipse");
    expect(shapes.find((s) => s.id === arrowId)?.type).toBe("rightArrow");
  });

  test("17c. shapes — deleteShape removes it", async () => {
    const id     = await engine.shapes.insertShape("ellipse", {});
    const before = (await engine.shapes.getShapes()).length;
    await engine.shapes.deleteShape(id);
    const after  = (await engine.shapes.getShapes()).length;
    expect(after).toBe(before - 1);
  });

  // ── 18. Find & replace ──────────────────────────────────────────────────────

  test("18. find and replace — global text substitution", async () => {
    await engine.document.insertParagraph(para("Placeholder: REPLACE_ME with real content."));
    await engine.document.findAndReplaceAll("REPLACE_ME", "the actual value");

    const xml = engine.zip.readAsText("word/document.xml")!;
    expect(xml).toContain("the actual value");
    expect(xml).not.toContain("REPLACE_ME");
  });

  // ── 19. Save ────────────────────────────────────────────────────────────────

  test("19. save — write final document to disk", async () => {
    await engine.saveToFile(OUTPUT);
    expect(fs.existsSync(OUTPUT)).toBe(true);
    expect(fs.statSync(OUTPUT).size).toBeGreaterThan(5_000);
    console.log(`\n✓ all-features.docx written to: ${OUTPUT}`);
  });

  // ── 20. Structural integrity ─────────────────────────────────────────────────

  test("20a. integrity — content types has all registered parts", () => {
    const ct = engine.zip.readAsText("[Content_Types].xml")!;
    expect(ct).toContain("wordprocessingml.document.main");
    expect(ct).toContain("wordprocessingml.styles");
    expect(ct).toContain("wordprocessingml.comments");
    expect(ct).toContain("wordprocessingml.footnotes");
  });

  test("20b. integrity — document rels has header, footer, and comments", () => {
    const rels = engine.zip.readAsText("word/_rels/document.xml.rels")!;
    expect(rels).toContain("relationships/header");
    expect(rels).toContain("relationships/footer");
    expect(rels).toContain("relationships/comments");
  });

  test("20c. integrity — word/comments.xml exists and contains reviewer comment", () => {
    const xml = engine.zip.readAsText("word/comments.xml");
    expect(xml).toBeTruthy();
    expect(xml).toContain("w:comments");
    expect(xml).toContain("Reviewer");
  });
});
