import { describe, test, expect, beforeAll } from "vitest";
import path from "path";
import fs from "fs";
import { Mdocxengine, Paragraph, Run, Table } from "@/index";

const INPUT  = path.resolve("samples/example.docx");
const OUTPUT = path.resolve("samples/outputs/complete-document.docx");

// Minimal 1×1 white PNG (67 bytes)
const TINY_PNG = Buffer.from(
  "89504e470d0a1a0a0000000d49484452000000010000000108020000009001" +
  "2e0000000c49444154789c6260f8cfc000000002000173e5494c0000000049454e44ae426082",
  "hex",
);

let engine: Mdocxengine;

describe("Complete document — headings, tables, media, headers/footers, references", () => {
  beforeAll(async () => {
    fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
    engine = await Mdocxengine.loadFromFile(INPUT);
  });

  // ─── Page Layout ──────────────────────────────────────────────────────────

  test("configure A4 portrait with normal margins", async () => {
    await engine.pageLayout.setPageSizePreset("A4", "portrait");
    await engine.pageLayout.setMarginPreset("normal");

    const size = await engine.pageLayout.getPageSize();
    const margins = await engine.pageLayout.getMargins();
    expect(size.orientation).toBe("portrait");
    expect(margins.top).toBe(1440);
  });

  // ─── Header & Footer ──────────────────────────────────────────────────────

  test("add a default header", async () => {
    const before = engine.header.headers.length;
    await engine.header.addHeader("mdocxengine — Complete Document", "default");
    expect(engine.header.headers.length).toBe(before + 1);

    const xml = engine.zip.readAsText("word/document.xml")!;
    expect(xml).toContain("w:headerReference");
  });

  test("add a default footer with page reference text", async () => {
    const before = engine.footer.footers.length;
    await engine.footer.addFooter("Page 1 | mdocxengine", "default");
    expect(engine.footer.footers.length).toBe(before + 1);

    const xml = engine.zip.readAsText("word/document.xml")!;
    expect(xml).toContain("w:footerReference");
  });

  // ─── Headings ─────────────────────────────────────────────────────────────

  test("insert Heading 1", async () => {
    const para = new Paragraph({ $: {}, "w:r": [] } as any);
    para.applyStyle("Heading1");
    para.addRun(Run.fromText("1. Introduction"));
    await engine.document.insertParagraph(para);

    const paragraphs = await engine.document.getParagraphs();
    const last = paragraphs[paragraphs.length - 1];
    expect(last.paragraph["w:pPr"]?.["w:pStyle"]?.["$"]?.["w:val"]).toBe("Heading1");
    expect(last.getRuns()[0].getText()).toBe("1. Introduction");
  });

  test("insert Heading 2", async () => {
    const para = new Paragraph({ $: {}, "w:r": [] } as any);
    para.applyStyle("Heading2");
    para.addRun(Run.fromText("1.1 Background"));
    await engine.document.insertParagraph(para);

    const paragraphs = await engine.document.getParagraphs();
    const last = paragraphs[paragraphs.length - 1];
    expect(last.paragraph["w:pPr"]?.["w:pStyle"]?.["$"]?.["w:val"]).toBe("Heading2");
  });

  test("insert Heading 3", async () => {
    const para = new Paragraph({ $: {}, "w:r": [] } as any);
    para.applyStyle("Heading3");
    para.addRun(Run.fromText("1.1.1 Motivation"));
    await engine.document.insertParagraph(para);

    const paragraphs = await engine.document.getParagraphs();
    const last = paragraphs[paragraphs.length - 1];
    expect(last.paragraph["w:pPr"]?.["w:pStyle"]?.["$"]?.["w:val"]).toBe("Heading3");
  });

  // ─── Body paragraphs ──────────────────────────────────────────────────────

  test("insert body paragraph with mixed formatting", async () => {
    const para = new Paragraph({ $: {}, "w:r": [] } as any);

    const plain = Run.fromText("This document was generated by ");
    const bold  = Run.fromText("mdocxengine");
    bold.setBold();
    bold.setColor("1F3864");
    const rest  = Run.fromText(", a TypeScript library for .docx manipulation.");

    para.addRun(plain);
    para.addRun(bold);
    para.addRun(rest);
    await engine.document.insertParagraph(para);

    const paragraphs = await engine.document.getParagraphs();
    const last = paragraphs[paragraphs.length - 1];
    expect(last.getRuns()[1].isBold()).toBe(true);
  });

  // ─── Table of Contents ────────────────────────────────────────────────────

  test("insert TOC at the top of the document", async () => {
    await engine.toc.insertTOC({ headingDepth: 3, title: "Table of Contents" }, 0);

    const xml = engine.zip.readAsText("word/document.xml")!;
    expect(xml).toContain("TOCHeading");
    expect(xml).toContain("TOC");
  });

  // ─── Table ────────────────────────────────────────────────────────────────

  test("insert a 3×3 table with headers", async () => {
    const raw = {
      $: {},
      "w:tr": [
        {
          "w:tc": [
            { "w:p": { "w:r": { "w:t": "Name" } } },
            { "w:p": { "w:r": { "w:t": "Role" } } },
            { "w:p": { "w:r": { "w:t": "Status" } } },
          ],
        },
        {
          "w:tc": [
            { "w:p": { "w:r": { "w:t": "Alice" } } },
            { "w:p": { "w:r": { "w:t": "Engineer" } } },
            { "w:p": { "w:r": { "w:t": "Active" } } },
          ],
        },
        {
          "w:tc": [
            { "w:p": { "w:r": { "w:t": "Bob" } } },
            { "w:p": { "w:r": { "w:t": "Designer" } } },
            { "w:p": { "w:r": { "w:t": "Active" } } },
          ],
        },
      ],
    };

    const table = new Table(raw as any);
    await engine.document.insertTable(table);

    const tables = await engine.document.getTables();
    expect(tables.length).toBeGreaterThan(0);
    const last = tables[tables.length - 1];
    expect(last.getRowCount()).toBe(3);
    expect(last.getColumnCount()).toBe(3);
    expect(last.getCellText(0, 0)).toBe("Name");
    expect(last.getCellText(1, 0)).toBe("Alice");
  });

  test("modify a table cell", async () => {
    const tables = await engine.document.getTables();
    const table = tables[tables.length - 1];
    table.setCellText(2, 2, "On Leave");
    expect(table.getCellText(2, 2)).toBe("On Leave");
  });

  test("add a row to the table", async () => {
    const tables = await engine.document.getTables();
    const table = tables[tables.length - 1];
    const before = table.getRowCount();
    table.addRow(["Carol", "Manager", "Active"]);
    expect(table.getRowCount()).toBe(before + 1);
    expect(table.getCellText(before, 0)).toBe("Carol");
  });

  // ─── Media ────────────────────────────────────────────────────────────────

  test("insert an image into the document", async () => {
    const { relId } = await engine.media.insertImage(TINY_PNG, "png");
    expect(relId).toBeTruthy();

    const images = engine.media.listImages();
    expect(images.length).toBeGreaterThan(0);
    expect(images.some((img) => img.name.endsWith(".png"))).toBe(true);
  });

  test("extract and re-insert an image", async () => {
    const images = engine.media.listImages();
    const first = images[0];
    const buf = engine.media.extractImage(first.name);
    expect(buf).not.toBeNull();
    expect(buf!.length).toBeGreaterThan(0);

    // Replace with the same bytes
    engine.media.replaceImage(first.name, TINY_PNG);
    const replaced = engine.media.extractImage(first.name);
    expect(replaced!.equals(TINY_PNG)).toBe(true);
  });

  // ─── Footnotes & Endnotes ─────────────────────────────────────────────────

  test("add a footnote and attach its run to a paragraph", async () => {
    const { id, run } = await engine.footnotes.addFootnote(
      "See Smith (2020) for a full derivation.",
    );
    expect(id).toBeGreaterThan(0);

    const para = new Paragraph({ $: {}, "w:r": [] } as any);
    para.addRun(Run.fromText("The result follows from first principles"));
    para.addRun(new Run(run));
    para.addRun(Run.fromText("."));
    await engine.document.insertParagraph(para);

    const footnotes = await engine.footnotes.getFootnotes();
    expect(footnotes.some((f) => f.text.includes("Smith"))).toBe(true);
  });

  test("add an endnote", async () => {
    const { id } = await engine.endnotes.addEndnote("For further reading see Appendix A.");
    expect(id).toBeGreaterThan(0);

    const endnotes = await engine.endnotes.getEndnotes();
    expect(endnotes.some((e) => e.text.includes("Appendix"))).toBe(true);
  });

  // ─── Cross-references ─────────────────────────────────────────────────────

  test("add a bookmark and create a cross-reference run", async () => {
    const paragraphs = await engine.document.getParagraphs();
    const idx = paragraphs.length - 1;
    const id = await engine.crossRef.addBookmark(idx, "sec_intro", "");
    expect(id).toBeGreaterThanOrEqual(0);

    const runs = engine.crossRef.createCrossRefRuns("sec_intro", "Introduction");
    expect(runs.length).toBe(5);
    expect((runs[1] as any)["w:instrText"]["_"]).toContain("REF sec_intro");
  });

  // ─── Citations ────────────────────────────────────────────────────────────

  test("add citation source and insert inline citation", async () => {
    await engine.citations.addSource({
      tag: "Jones2019",
      sourceType: "Book",
      author: "Jones",
      title: "Advanced Document Processing",
      year: "2019",
      publisher: "Tech Press",
    });

    const sources = await engine.citations.getSources();
    expect(sources.find((s) => s.tag === "Jones2019")).toBeDefined();

    const citRuns = engine.citations.createCitationRuns("Jones2019");
    expect(citRuns.length).toBe(5);

    // Insert a paragraph with the citation
    const para = new Paragraph({ $: {}, "w:r": [] } as any);
    para.addRun(Run.fromText("According to prior work "));
    citRuns.forEach((r) => para.addRun(new Run(r)));
    para.addRun(Run.fromText("."));
    await engine.document.insertParagraph(para);
  });

  test("insert bibliography", async () => {
    await engine.citations.insertBibliography();
    const xml = engine.zip.readAsText("word/document.xml")!;
    expect(xml).toContain("BIBLIOGRAPHY");
  });

  // ─── Save ─────────────────────────────────────────────────────────────────

  test("save complete document to disk", async () => {
    await engine.saveToFile(OUTPUT);
    expect(fs.existsSync(OUTPUT)).toBe(true);
    const stat = fs.statSync(OUTPUT);
    expect(stat.size).toBeGreaterThan(0);
    console.log(`\n✓ Output written to: ${OUTPUT}`);
  });
});
